### PR TITLE
implement external timestamp for mock pd

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

This PR should be merged before https://github.com/tikv/client-go/pull/610.

It only implements mock function for it, without upgrading the pd client dependency, so that it will not break the CI (as the mock region in TiDB hasn't implemented these functions).

### CODE REVIEW

**Comment by YangKeao** [comment]
ref https://github.com/tikv/pd/pull/5631

**Comment by YangKeao** [comment]
It's meaningless to split this PR, it still cannot fix the CI, as it still requires TiDB mockstore to implement PDClient.

**Comment by YangKeao** [comment]
It's meaningless to split this PR, it still cannot fix the CI, as it still requires TiDB mockstore to implement PDClient.

**Comment by YangKeao** [comment]
Oops. I could implement but doesn't upgrade pd client :+1: .

**Review by lhy1024 — APPROVED** [review]

**Comment by YangKeao** [comment]
/cc @disksing 

PTAL

**Review by HunDunDM — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
