### PR TITLE
add util to set dns server

### PR DESCRIPTION
**Pull request by Smityz**
solve https://github.com/tikv/client-go/issues/829

I have provided a tool for client-go that allows for the customization of DNS server addresses. This way, by only exposing the coreDNS address of the k8s cluster, it is possible to achieve client access to tikv across k8s clusters.

### CODE REVIEW

**Comment by disksing** [comment]
Hi, I don't see the option to set it. Do you forget to add some file?

**Comment by Smityz** [comment]
```golang
package main

import (
	"context"
	"fmt"

	"github.com/tikv/client-go/v2/rawkv"
	"github.com/tikv/client-go/v2/util"
	pd "github.com/tikv/pd/client"
	"google.golang.org/grpc"
)

func main() {
	coreDNSAddr := "8.8.8.8:53"
	domain := "cluster.local"
	dialer := grpc.WithContextDialer(util.GetCustomDNSDialer(coreDNSAddr, domain))
	cli, err := rawkv.NewClientWithOpts(
		context.TODO(),
		[]string{"pd0.pd:2379"},
		rawkv.WithPDOptions(pd.WithGRPCDialOptions(dialer)),
		rawkv.WithGRPCDialOptions(dialer),
	)
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	fmt.Printf("cluster ID: %d\n", cli.ClusterID())
}
```
Can you compile these codes on my branch?

**Comment by Smityz** [comment]
@disksing Hi master, do you have time to help me review this PR?

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
thanks @Smityz

**Pull request merged**
