### PR TITLE
fit witness

### PR DESCRIPTION
**Pull request by ethercflow**
Modify:
- Skip the witnesses when gen region cache unless the witness is the leader
- Retry on IsWitness error

ref tikv/tikv#12876

Signed-off-by: Wenbo Zhang <ethercflow@gmail.com>

### CODE REVIEW

**Comment by ethercflow** [comment]
@Connor1996 PTAL, thanks!

**Review by Connor1996 — COMMENTED** [review]
Need to cover it in test

**Comment by ethercflow** [comment]
> Need to cover it in test

Added, thanks!

**Comment by ethercflow** [comment]
CI failed as need to update TiDB's go mod

**Comment by ethercflow** [comment]
@sticnarf PTAL, thanks!

**Review by sticnarf — APPROVED** [review]
LGTM

**Pull request merged**
