### PR TITLE
rawkv: Added back `ScanOption` from `v1` but with a more standard Golang pattern

### LINKED ISSUE #401: [2.0] `rawkv` ScanOption migration
I'm upgrading some code to the new TiKV v2.0 version (`v2.0.0-rc`).

The `v1` version has a [ScanOption](https://github.com/tikv/client-go/blob/v1/rawkv/rawkv.go#L314) support that seems to have disappeared in `v2`. Is it just an oversight and I can push a PR that would add that back? Is there anything else to consider here?

I was using it to perform a `KeyOnly` scan on some table.

### PR DESCRIPTION
**Pull request by maoueh**
This enables specifying:
- `ScanKeyOnly`
- `ScanColumnFamily`

Fixes #401 

#### Notes

This could also be used to remove the `ReverseScan` version and `ScanReverse` option could be used. It could be argue that `ReverseScan` is more discoverable. Happy to remove if it's decided that `ScanReverse` is discoverable enough.

### CODE REVIEW

**Comment by disksing** [comment]
Thanks @maoueh

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
Hi @maoueh , there are some lint warnings need to fix.
```
  Error: exported type `ScanOption` should have comment or be unexported (golint)
  Error: exported function `ScanKeyOnly` should have comment or be unexported (golint)
  Error: exported function `ScanColumnFamily` should have comment or be unexported (golint)
```

**Comment by maoueh** [comment]
I'll fix the linting issues today.

**Comment by maoueh** [comment]
Linting issues should be fixed now.

**Comment by maoueh** [comment]
@disksing Linting issues fixed, the CI is still in error but I imagine is unrelated to this PR.

**Comment by disksing** [comment]
The `Compatibility Test` is only to inform us to update tidb and it will not block PR. Would you like to update your branch so I can merge it?

**Comment by maoueh** [comment]
Branch updated.

**Pull request merged**
