### PR TITLE
internal/retry: export backoff errors

### PR DESCRIPTION
**Pull request by tutububug**

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
@tutububug please add DCO and fix lint issues.

**Comment by tutububug** [comment]
> @tutububug please add DCO and fix lint issues.

ok, I'll close this PR and open a new one(#934) to fix the inspection issues, because of encountered many rebase conflicts.

**Comment by Smityz** [comment]
> 

No need to open a new PR, you can push -f your branch of this PR.
Opening a new PR may cause misleading.

**Comment by tutububug** [comment]
> 

Because the master branch code that this pr is based on is relatively early, it needs to be rebased with the latest master code. During the rebase process, there is a lot of go.mod modifications, so it is directly closed.

**Pull request closed without merging**
