### PR TITLE
*: Update pd client

### PR DESCRIPTION
**Pull request by CabinfeverB**

### CODE REVIEW

**Comment by nolouch** [comment]
Compatibility Test failed, is it normal?

**Comment by disksing** [comment]
> Compatibility Test failed, is it normal?

it is ok. we can update tidb later.

**Comment by cfzjywxk** [comment]
After this pr, the tidb master branch(https://github.com/pingcap/tidb/commit/6e8eb6ef7729763033c4953c53b51cd7f2714d7f) could not be compiled with the newest client-go version, errors would be reported:
```
go: finding module for package github.com/tikv/pd/client/resource_manager/client
github.com/pingcap/tidb/store/driver imports
	github.com/tikv/pd/client/resource_manager/client: module github.com/tikv/pd/client@latest found (v0.0.0-20230302081710-2ae62af1aaaa), but does not contain package github.com/tikv/pd/client/resource_manager/client
```
Something wrong with the dependency.
@CabinfeverB @nolouch 
PTAL

**Comment by CabinfeverB** [comment]
> After this pr, the tidb master branch([pingcap/tidb@6e8eb6e](https://github.com/pingcap/tidb/commit/6e8eb6ef7729763033c4953c53b51cd7f2714d7f)) could not be compiled with the newest client-go version, errors would be reported:
> 
> ```
> go: finding module for package github.com/tikv/pd/client/resource_manager/client
> github.com/pingcap/tidb/store/driver imports
> 	github.com/tikv/pd/client/resource_manager/client: module github.com/tikv/pd/client@latest found (v0.0.0-20230302081710-2ae62af1aaaa), but does not contain package github.com/tikv/pd/client/resource_manager/client
> ```
> 
> Something wrong with the dependency. @CabinfeverB @nolouch PTAL

https://github.com/pingcap/tidb/pull/41677 will fix it

**Pull request merged**
