### PR TITLE
txn: change IsUnnecessaryKeyValue interface to report error for unexpected paths

### PR DESCRIPTION
**Pull request by cfzjywxk**
ref: [#30410](https://github.com/pingcap/tidb/issues/30410)
ref: https://github.com/pingcap/tidb/pull/30447

Try to add enhancement check logic for unnecessary key-value pairs, report error if unexpected situations are encountered.

Signed-off-by: cfzjywxk <lsswxrxr@163.com>

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@youjiali1995 PTAL

**Review by youjiali1995 — APPROVED** [review]

**Comment by youjiali1995** [comment]
The integration test depends on TiDB and client-go. Maybe you need to wrap it to pass tests and then remove the wrapper after TiDB is updated.
```
		have IsUnnecessaryKeyValue([]byte, []byte, "github.com/tikv/client-go/v2/kv".KeyFlags) bool
		want IsUnnecessaryKeyValue([]byte, []byte, "github.com/tikv/client-go/v2/kv".KeyFlags) (bool, error)
```

**Review by you06 — APPROVED** [review]
LGTM

**Comment by cfzjywxk** [comment]
@disksing 
Could we run the ci test with specific tidb pr or merge the breaking change directly with tidb pr?

**Comment by disksing** [comment]
@cfzjywxk You can update tidb version to your PR here.

**Comment by cfzjywxk** [comment]
> @cfzjywxk You can update tidb version to your PR here.

@disksing 
PTAL, the compatibililty test has passed expect the tidb-repo build test without updaing the `go.mod`.

**Pull request merged**
