### PR TITLE
support time detail v2

### PR DESCRIPTION
**Pull request by glorv**
- Change time unit from ms to ns in TimeDetailV2 for more accurate statistics
- Add ProcessSuspendWallTime field to track the waiting time in threadpool scheduling.

Related change in tikv side is https://github.com/tikv/tikv/pull/14358.

### CODE REVIEW

**Comment by glorv** [comment]
@Connor1996 @disksing PTAL

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@rleungx PTAL

**Comment by glorv** [comment]
@disksing PTAL

**Review by nolouch — APPROVED** [review]
lgtm. @Connor1996  plz help to merge.

**Comment by Connor1996** [comment]
tidb-compatibility test failed

**Comment by glorv** [comment]
> tidb-compatibility test failed

@Connor1996 The compatible test failed is expected because I changed a public interface, need to update tidb to fix build.

**Pull request merged**
