### PR TITLE
*: make grpc request duration more accurate

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu jackysp@gmail.com
In `SendRequest`, the metrics of `tidb_tikvclient_request_seconds` will include the duration of batch client recycle and reconnection, which may make it not accurate for the real RPC duration.
Move it before the send RPC request and add a new metrics for the batch client recycle and reconnection.

### CODE REVIEW

**Review by lysu — APPROVED** [review]

**Comment by lysu** [comment]
how about add new metric for recycleIdleConnArray?- -

**Comment by disksing** [comment]
Hi, @jackysp please add DCO for your commits.

**Comment by jackysp** [comment]
> how about add new metric for recycleIdleConnArray?- -

Maybe next one.

**Comment by disksing** [comment]
Thanks @jackysp , I'll update your branch before merge.

**Pull request merged**
