### PR TITLE
*: remove dangling gocheck usages

### PR DESCRIPTION
**Pull request by tisonkun**
ref #97

cc @disksing

### CODE REVIEW

**Comment by tisonkun** [comment]
2021-06-24T15:17:35.9114142Z --- FAIL: TestConn (0.00s)

I don't think it has anything to do with this PR.

**Comment by disksing** [comment]
test race fixed here: https://github.com/tikv/client-go/pull/168

**Comment by disksing** [comment]
Hi @tisonkun , would you like to rename `NewTestStoreT` to `NewTestStore` and rename all references?

**Comment by tisonkun** [comment]
> Hi @tisonkun , would you like to rename `NewTestStoreT` to `NewTestStore` and rename all references?

Updated.

Thanks for fixing the race issue. Please notify me if it is merged.

**Review by disksing — APPROVED** [review]

**Pull request merged**
