### PR TITLE
tikv: remove BeginWithOption method

### PR DESCRIPTION
**Pull request by gotoxu**
Signed-off-by: Xu Qiaolun <jamesxql@gmail.com>

### CODE REVIEW

**Comment by disksing** [comment]
We have to reset the tidb version in integration test to latest tidb master.

**Comment by gotoxu** [comment]
> We have to reset the tidb version in integration test to latest tidb master.

I'll handle it

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
Thanks @gotoxu

**Pull request merged**
