### PR TITLE
txnkv: `RangedKVRetriever` struct to provide custom range data operations

### PR DESCRIPTION
**Pull request by lcwangchao**
Refer: https://github.com/pingcap/tidb/issues/26952

To make a better implement for temporary table. It is required that snapshot can read data from other sources like memory for some specified ranges. So we expect `KVSnapshot` can provide some methods to override data fetch.

The draft has been proposed here: #262 . This pr is the first step, introduce a struct to provide custom range data operations. 

Signed-off-by: Chao Wang <cclcwangchao@hotmail.com>

### CODE REVIEW

**Comment by disksing** [comment]
It seems the new method
```
Scan(startKey []byte, endKey []byte, reverse bool) (Iterator, error)
```
is almost the same like the combination of the two old methods (except for ReverseIter does not have bound)
```
Iter(k []byte, upperBound []byte) (Iterator, error)
IterReverse(k []byte) (Iterator, error)
```

Is it possible to merge them together?

**Comment by lcwangchao** [comment]
> It seems the new method
> 
> ```
> Scan(startKey []byte, endKey []byte, reverse bool) (Iterator, error)
> ```
> 
> is almost the same like the combination of the two old methods (except for IterReverse does not have bound)
> 
> ```
> Iter(k []byte, upperBound []byte) (Iterator, error)
> IterReverse(k []byte) (Iterator, error)
> ```
> 
> Is it possible to merge them together?

They are a little different for iter reverse. For `Scan` it can support both start and end are not nil, it is a required feature. But current `IterReverse` do not support it.

**Comment by disksing** [comment]
> > It seems the new method
> > ```
> > Scan(startKey []byte, endKey []byte, reverse bool) (Iterator, error)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is almost the same like the combination of the two old methods (except for IterReverse does not have bound)
> > ```
> > Iter(k []byte, upperBound []byte) (Iterator, error)
> > IterReverse(k []byte) (Iterator, error)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it possible to merge them together?
> 
> They are a bit different for iter reverse. For `Scan` it can support both start and end are not nil, it is a required feature. But current `IterReverse` do not support it.

Can we add `lowerBound` to `IterReverse`?

**Comment by lcwangchao** [comment]
> > > It seems the new method
> > > ```
> > > Scan(startKey []byte, endKey []byte, reverse bool) (Iterator, error)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > is almost the same like the combination of the two old methods (except for IterReverse does not have bound)
> > > ```
> > > Iter(k []byte, upperBound []byte) (Iterator, error)
> > > IterReverse(k []byte) (Iterator, error)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is it possible to merge them together?
> > 
> > 
> > They are a bit different for iter reverse. For `Scan` it can support both start and end are not nil, it is a required feature. But current `IterReverse` do not support it.
> 
> Can we add `lowerBound` to `IterReverse`?

I think it's a good idea. I searched the current code, only `uSnapshot` delecars a method `IterReverse` but its a internal interface. Adding `lowerBound` to `IterReverse` for `Retriever` is fine.
```
Iter(k []byte, upperBound []byte) (Iterator, error)
IterReverse(k []byte, lowerBound []byte) (Iterator, error)
```
If one day

**Comment by lcwangchao** [comment]
Done

**Comment by lcwangchao** [comment]
@disksing  PTAL again

**Comment by lcwangchao** [comment]
It should moved to tidb if it is currently only used by temporary table

**Pull request closed without merging**
