### PR TITLE
Introduce the FlashbackNotPrepared error

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### CODE REVIEW

**Review by Defined2014 — APPROVED** [review]

**Comment by disksing** [comment]
It looks there is somethong wrong with integration test. Could you check why it is failing?

**Comment by Connor1996** [comment]
> Signed-off-by: JmPotato [ghzpotato@gmail.com](mailto:ghzpotato@gmail.com)
> 
> Since the flashback state check is before other checks like EpochNotMatch, so we need to invalidate the region cache also.

Why not move the order of the check after `EpochNotMatch`?

**Comment by JmPotato** [comment]
> It looks there is somethong wrong with integration test. Could you check why it is failing?

I think it's the same problem as https://github.com/tikv/client-go/issues/449.

**Pull request merged**
