### PR TITLE
add metrics for stale-read traffic

### PR DESCRIPTION
**Pull request by you06**
Add the traffic metrics for stale-read, this tells the hit ratio and traffics produced by stale-read miss.

The metrics example:

image

Before 15:15, the stale-read hit ratio is high, and after 15:15, there are over 80% stale-read misses.

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

**Comment by zyguan** [comment]
BTW, do we need/have metrics for retry traffic?

**Comment by you06** [comment]
> retry traffic

You mean the retry traffic should be counted multi times?

**Comment by zyguan** [comment]
> > retry traffic
> 
> You mean the retry traffic should be counted multi times?

No, I think it's ok for only tracking the final req/resp (as the current implementation does). I just wonder that is it necessary for observing retry traffic as well (maybe by another metric).

**Comment by disksing** [comment]
Merged! If we decide to add metrics later, please submit a new PR. Thanks!

**Pull request merged**
