### PR TITLE
*: disable PermitWithoutStream to avoid too many pings

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Jack Yu <jackysp@gmail.com>

close: https://github.com/pingcap/tidb/issues/36861

### CODE REVIEW

**Comment by jackysp** [comment]
TiDB may connect itself to get some info via grpc protocol, such as cluster_xx tables in information_schema database.

**Comment by sticnarf** [comment]
I'm curious what was the original intention of setting `PermitWithoutStream: true`? In other words, what regression might this change bring to us?

**Comment by disksing** [comment]
As I remember, keepalive is introduced to avoid the case when tikv is not working and client-go doesn't know about it, it may waste some time by sending requests to tikv.

**Comment by jackysp** [comment]
I think tidb-server introduced a new way https://github.com/pingcap/tidb/pull/14145 to detect if tikv-server is alive or not.

**Comment by disksing** [comment]
@jackysp maybe we can make it a configure option like `keepAlive` and `keepAliveTimeout` and make it use `true` by default so other users that don't handle it by themselves won't be affected.

**Comment by disksing** [comment]
As tikv-server does not enable `keepalive_permit_without_calls`, this option has no effect and can be removed safely.

**Pull request merged**
