### PR TITLE
Add miss register for TiKVUnsafeDestroyRangeFailuresCounterVec

### PR DESCRIPTION
**Pull request by july2993**
`TiKVUnsafeDestroyRangeFailuresCounterVec` seems forget to register

### CODE REVIEW

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by you06** [comment]
I meet this error by registering `TiKVUnsafeDestroyRangeFailuresCounterVec`.

```
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000060120, {0xc00046f440, 0x1, 0x39c565a})
        /home/you06/workspace/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:400 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
        /home/you06/workspace/go/pkg/mod/github.com/prometheus/client_golang@v1.5.1/prometheus/registry.go:177
github.com/tikv/client-go/v2/metrics.RegisterMetrics()
        /home/you06/workspace/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc.0.20211229051614-62d6b4a2e8f7/metrics/metrics.go:608 +0x17cc
github.com/pingcap/tidb/metrics.RegisterMetrics()
        /home/you06/workspace/go/src/github.com/pingcap/tidb/metrics/metrics.go:163 +0x2b2b
main.registerMetrics(...)
        /home/you06/workspace/go/src/github.com/pingcap/tidb/tidb-server/main.go:281
main.main()
        /home/you06/workspace/go/src/github.com/pingcap/tidb/tidb-server/main.go:175 +0x2e5
```

It seems it's already registered here.

https://github.com/pingcap/tidb/blob/8193c465c84fc12cfa0d71eecebf153b285f45b6/metrics/metrics.go#L142

**Comment by sticnarf** [comment]
> It seems it's already registered here.

Then, we may not register it in TiDB. I think @july2993 wants to use it outside of TiDB...

**Comment by you06** [comment]
> Then, we may not register it in TiDB. I think @july2993 wants to use it outside of TiDB...

Yeah, the registration in TiDB needs to be removed.

**Pull request merged**
