### PR TITLE
client_batch: add test for auto re-connect idle connection when wait connection ready and fix ci

### PR DESCRIPTION
**Pull request by crazycs520**
Since master branch already fix the issue #833 in PR #665, this PR only add some test and refine code to keep code consistent across versions.

releated PR: 
- https://github.com/tikv/client-go/pull/833
- https://github.com/tikv/client-go/pull/834
- https://github.com/pingcap/tidb/pull/44593

### CODE REVIEW

**Review by zyguan — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@crazycs520 
The CI seems to be broken for other reasons...

**Comment by crazycs520** [comment]
> @crazycs520 The CI seems to be broken for other reasons...

I'm trying to fix it.

**Pull request merged**
