### PR TITLE
fix RawBatchPutRequest forward compatibility

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

RawBatchPutRequest has forward compatibility issues. This pull request merge this two version into one message and update the request constructor to support the older version of TiKV (< 5.3.0)

Old version used in TiKV < 5.3.0:
```protobuf
message RawBatchPutRequest {
    Context context = 1;
    repeated KvPair pairs = 2;
    string cf = 3;
    uint64 ttl = 4;
    bool for_cas = 5;
}
```
New version used in TiKV 5.3.0:
```protobuf
message RawBatchPutRequest {
    Context context = 1;
    repeated KvPair pairs = 2;
    string cf = 3;
    // The time-to-live for each keys in seconds, and if the length of `ttls`
    // is exactly one, the ttl will be applied to all keys. Otherwise, the length
    // mismatch between `ttls` and `pairs` will return an error.
    repeated uint64 ttls = 4;
    bool for_cas = 5;
}
```

Now, to be compatible with these two version, we modify this message into:

```protobuf
message RawBatchPutRequest {
    Context context = 1;
    repeated KvPair pairs = 2;
    string cf = 3;
    bool for_cas = 5;
	uint64 ttl = 4 [deprecated = true];
    // The time-to-live for each keys in seconds, and if the length of `ttls`
    // is exactly one, the ttl will be applied to all keys. Otherwise, the length
    // mismatch between `ttls` and `pairs` will return an error.
    repeated uint64 ttls = 6;
```

related: 
- [x] https://github.com/tikv/client-java/pull/441
- [x] https://github.com/tikv/client-java/issues/419

### CODE REVIEW

**Comment by sticnarf** [comment]
The new proto in this PR description seems not correct? `ttls` should be assigned a new number according to https://github.com/tikv/client-go/pull/403?

**Comment by sticnarf** [comment]
Is there any test for RawKV TTL in this client?

**Comment by iosmanthus** [comment]
> Is there any test for RawKV TTL in this client?

Yes, running tests with `-with-tikv` will trigger the TTL test. But no tests to cover TiKV compatibility for now.

**Comment by iosmanthus** [comment]
> The new proto in this PR description seems not correct? `ttls` should be assigned a new number according to #403?

Sorry, seems the PR description has ambiguity, I update to clarify the versions of `proto` files.

**Review by sticnarf — APPROVED** [review]
LGTM.

**Comment by sticnarf** [comment]
@disksing PTAL when you're free because the new format is suggested by you.

**Pull request merged**
