### PR TITLE
Add PrefixNextKey API (#105)

### PR DESCRIPTION
**Pull request by gotoxu**
Signed-off-by: Xu Qiaolun <jamesxql@gmail.com>

fix issue: #105

### CODE REVIEW

**Comment by disksing** [comment]
Any idea about this issue? https://github.com/pingcap/tidb/issues/12598

**Comment by gotoxu** [comment]
> Any idea about this issue? [pingcap/tidb#12598](https://github.com/pingcap/tidb/issues/12598)
> Maybe return empty slice is more correct but I don't know if it can break anything.

Do you know why tidb still has not fixed this bug?

**Comment by disksing** [comment]
I have no idea. Maybe we can fix it here and in the comment, we declare that it is different from TiDB.

**Comment by gotoxu** [comment]
@disksing I fixed it and stated in the comments

**Comment by gotoxu** [comment]
Please deal with this PR as soon as possible, we need to use this API, thank you!

/cc @disksing

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
Thanks @gotoxu

**Pull request merged**
