### PR TITLE
log: only log the first lock in every flush or prewrite response

### LINKED ISSUE #595: `prewrite encounters lock` log is noisy
```
root@cloud-ecosystem-00:~/cluster/cloud/sys-test-16/tidb-0# wc -l tidb-2022-10-10T23-40-54.065.log
640243 tidb-2022-10-10T23-40-54.065.log
root@cloud-ecosystem-00:~/cluster/cloud/sys-test-16/tidb-0# grep 'prewrite encounters lock' tidb-2022-10-10T23-40-54.065.log | wc -l
548084
```

### PR DESCRIPTION
**Pull request by ekexium**
close #595 
1 lock is enough for most of the cases.

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
Actually, this does help us in some corner case investigations before.
Currently, without persisted lock view it seems to be difficult to analyze conflict problems.
/cc @MyonKeminta

**Comment by ekexium** [comment]
> Actually, this does help us in some corner case investigations before. Currently, without persisted lock view it seems to be difficult to analyze conflict problems. /cc @MyonKeminta

There may be other solutions to that balance log verbosity and information-richness. One worth consideration might be "for each conflicting ts, only log 1 key". How about that

**Review by you06 — APPROVED** [review]

**Comment by cfzjywxk** [comment]
> > Actually, this does help us in some corner case investigations before. Currently, without persisted lock view it seems to be difficult to analyze conflict problems. /cc @MyonKeminta
> 
> There may be other solutions that balance log verbosity and information-richness. One worth consideration might be "for each conflicting ts, only log 1 key". How about that?

It looks fine.

**Comment by cfzjywxk** [comment]
> > > Actually, this does help us in some corner case investigations before. Currently, without persisted lock view it seems to be difficult to analyze conflict problems. /cc @MyonKeminta
> > 
> >

> > There may be other solutions that balance log verbosity and information-richness. One worth consideration might be "for each conflicting ts, only log 1 key". How about that?
> 
> 


It looks fine.

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
