### PR TITLE
batchput add ttl to every key

### PR DESCRIPTION
**Pull request by daimashusheng**
my issue: https://github.com/pingcap/kvproto/issues/807

I add ttls param for BatchPut request so that it can set independent ttl for every key

### CODE REVIEW

**Comment by disksing** [comment]
no need to update kvproto?

**Comment by tisonkun** [comment]
@daimashusheng please elaborate the background of this PR or create an issue for it.

**Comment by disksing** [comment]
LGTM. I guess we need to wait for TiKV's PR be merged first.

**Review by iosmanthus — APPROVED** [review]
LGTM, @disksing PTAL and the issue that block the CI

**Pull request merged**
