### PR TITLE
go.mod: update pd/client

### PR DESCRIPTION
**Pull request by Defined2014**
for issue https://github.com/pingcap/tidb/issues/36505, it got an incorrect clusterID which be fixed by https://github.com/tikv/pd/pull/5281, so need update pd/client for `client-go` and `tidb-server`

### CODE REVIEW

**Comment by Defined2014** [comment]
@you06 @sticnarf 
PTAL~

**Comment by sticnarf** [comment]
CI fails complaining  `go.mod` needs updating.

**Comment by Defined2014** [comment]
> CI fails complaining `go.mod` needs updating.

Done.

**Comment by you06** [comment]
Need to impl `SplitAndScatterRegions` for mock client in PD before this PR?

**Comment by Defined2014** [comment]
> Need to impl `SplitAndScatterRegions` for mock client in PD before this PR?

Updated.

**Comment by Defined2014** [comment]
@sticnarf @you06 PTAL.
I think `tidb-compatibility` test which depends on tidb master branch is not required. I'll update tidb repo later.

**Review by you06 — APPROVED** [review]

**Pull request merged**
