### PR TITLE
do not try leader if it's unreachable

### PR DESCRIPTION
**Pull request by zyguan**
pick https://github.com/tikv/client-go/pull/949

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@zyguan Please resolve the conflicts

**Review by cfzjywxk — APPROVED** [review]

**Review by ekexium — APPROVED** [review]

**Comment by cfzjywxk** [comment]
A failure test
```
--- FAIL: TestRegionRequestToSingleStore (5.20s)
    --- FAIL: TestRegionRequestToSingleStore/TestKVReadTimeoutWithDisableBatchClient (0.08s)
        region_request_test.go:732: 
            	Error Trace:	/home/runner/work/client-go/client-go/internal/locate/region_request_test.go:732
            	Error:      	Not equal: 
            	            	expected: 0
            	            	actual  : 1
            	Test:       	TestRegionRequestToSingleStore/TestKVReadTimeoutWithDisableBatchClient
```

**Comment by zyguan** [comment]
> A failure test
> 
> ```
> --- FAIL: TestRegionRequestToSingleStore (5.20s)
>     --- FAIL: TestRegionRequestToSingleStore/TestKVReadTimeoutWithDisableBatchClient (0.08s)
>         region_request_test.go:732: 
>             	Error Trace:	/home/runner/work/client-go/client-go/internal/locate/region_request_test.go:732
>             	Error:      	Not equal: 
>             	            	expected: 0
>             	            	actual  : 1
>             	Test:       	TestRegionRequestToSingleStore/TestKVReadTimeoutWithDisableBatchClient
> ```

The test is flaky, there might be a backoff when the mock server is not ready.

**Comment by cfzjywxk** [comment]
@zyguan 
The DCO of CI fails.

**Review by you06 — APPROVED** [review]

**Pull request merged**
