### PR TITLE
reset resolvedLocks when setting snapshot ts

### PR DESCRIPTION
**Pull request by sticnarf**
This PR intends to fix the jepsen failure https://github.com/tikv/tikv/issues/10552#issuecomment-879531922.

If the `minCommitTS` of some transaction was advanced before, and the snapshot timestamp is reset, we must also reset the `resolvedLocks`. Otherwise, the reader can read a stale result if only the primary lock is committed. (See the test as an example)

### CODE REVIEW

**Comment by sticnarf** [comment]
PTAL @cfzjywxk @tiancaiamao

**Comment by cfzjywxk** [comment]
> PTAL @cfzjywxk @tiancaiamao

@tiancaiamao @sticnarf 
Maybe we need to check other places in which the initialization logic is changed or some objects are resued, as they could affect the correctness because of some implicit dependencies or connections.

**Review by jackysp — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Comment by sticnarf** [comment]
There is already a https://github.com/pingcap/br/pull/1354 fixing the BR compatibility failure, fix anyway.

**Pull request merged**
